create or replace transient table nyc_taxi (
    vendor_id string not null, 
    tpep_pickup_ts timestamp_ntz not null, 
    tpep_dropoff_ts timestamp_ntz not null, 
    tpep_pickup_date date not null, 
    tpep_dropoff_date date not null, 
    passenger_count integer, 
    trip_distance number(15, 2),
    pickup_longitude number(15, 2),
    pickup_latitude number(15, 2),
    rate_code_id integer, 
    store_and_fwd_flag string, 
    pu_location_id integer,
    do_location_id integer,
    payment_type integer,
    fare_amount number(38, 2),
    extra number(15, 1), 
    mta_tax number(15, 1),
    tip_amount number(15, 2),
    tolls_amount number(15, 2), 
    improvement_surcharge number(15, 1),
    total_amount number(15, 2),
    create_process string not null,
    create_ts timestamp_ntz not null
)
as
select
    vendorid::string, 
    tpep_pickup_datetime::timestamp_ntz, 
    tpep_dropoff_datetime::timestamp_ntz, 
    tpep_pickup_datetime::date, 
    tpep_dropoff_datetime::date, 
    passenger_count::integer, 
    trip_distance::number(15, 2),
    pickup_longitude::number(15, 2),
    pickup_latitude::number(15, 2),
    ratecodeid::integer, 
    store_and_fwd_flag::string, 
    pulocationid::integer,
    dolocationid::integer,
    payment_type::integer,
    fare_amount::number(38, 2),
    extra::number(15, 1), 
    mta_tax::number(15, 1),
    tip_amount::number(15, 2),
    tolls_amount::number(15, 2), 
    improvement_surcharge::number(15, 1),
    total_amount::number(15, 2),
    'Airflow snowflake_analytics Dag'::string,
    convert_timezone('UTC' , current_timestamp )::timestamp_ntz
from raw.public.nyc_taxi_raw;